[package]
name = "nutexb_swizzle_cli"
version = "0.1.0"
authors = ["ScanMountGoat <>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
nutexb_swizzle = { path = "../nutexb_swizzle" }